# Generated by Django 3.0.6 on 2020-05-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yamls',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
