# Generated by Django 3.0.6 on 2020-05-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_project', '0003_actiontemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontemplates',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (1, '禁用')], default=0),
        ),
    ]
