# Generated by Django 3.0.6 on 2020-05-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_project', '0004_actiontemplates_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
