# Generated by Django 3.0.6 on 2020-05-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_project', '0005_userlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
